### ISSUE TITLE
ibmiotapp config node (type == "ibmiot") cannot be created by POST to /flows due to credentials handling

### ISSUE THREAD

**Issue by piotrpad** [ibm-watson-iot/iot-nodered#28]
Hi,
I'm implementing a system that deploys flows to node-red (bluemix and "local") and I previously used mqlight input and output nodes for communication and after some education (that is reding the source code etc.) I was able to succesfully deploy config nodes for mqligh to node-red using post to /flows. Then I tried (well, I actually need to) use ibmiotf connector and failed. It seems this node is handling credentials in some special way - not really as advised in node-red manual, and cannot get them from single post with all the flow data. I'm not node-red not js expert so I may be wrong, or simply do not know how to prepare correct json, but I guess this behaviour renders impossible creation of flows with ibmiot node(s)  via single post to /flows (I need automated creation, I'm not able to "pre-deploy" and then manually fill-in the credentials).

Example post for working flow with mqlight connector, so we are on the same page, credentials are passed created in node with id 1694819250, I need, in a similar way, to create ibmiot nodes:

```
[{"type":"tab","id":"1365202186","label":"Flow1"},
{"id":"1651191114","z":"1365202186","x":80,"y":20,"payloadType":"date","payload":"","once":false,"crontab":"","repeat":"1","name":"source","topic":"","type":"inject","wires":[["1586600255"]]},
{"id":"1586600255","z":"1365202186","x":300,"y":20,"outputs":1,"func":"msg.payload =  msg.payload * 0.002 + 7.0 ;\nreturn msg;","name":"0","type":"function","wires":[["474675244"]]},
{"id":"474675244","z":"1365202186","x":520,"y":20,"service":"1694819250","name":"graph out connector","topic":"/gs/data","type":"mqlight out","wires":[[]]},
{"id":"1694819250","z":"1365202186","x":740,"y":20,"clientid":"","credentials":{"user":"uuuuuuuuu","password":"************"},"service":"amqps://mqlightprod-ag-00030a.services.dal.bluemix.net:2901","type":"mqlight service"}]
```
and similar with "ibmiot in" and "ibmiot" (not working due to credentials being lost):
```
[{"type":"tab","id":"1365202186","label":"Flow19"},
{"id":"1651191114","z":"1365202186","x":80,"y":20,"deviceType":"+","allEvents":true,"commandType":"","apiKey":"1694819250","allApplications":"","format":"json","eventType":"+","type":"ibmiot in","deviceId":"","allFormats":true,"service":"registered","name":"graph in connector","inputType":"evt","allCommands":"","applicationId":"","allDevices":true,"allDeviceTypes":true,"authentication":"apiKey","wires":[["1586600255"]]},
{"id":"1586600255","z":"1365202186","x":300,"y":20,"console":"false","name":"sink","active":true,"type":"debug","complete":"false","wires":[[]]},
{"id":"1694819250","z":"1365202186","x":520,"y":20,"password":"tokentokentoken","keepalive":60,"name":"MyIOTF","cleansession":true,"type":"ibmiot","user":"a-org-key"}]
```

**Comment by Lokesh-K-Haralakatta** [comment]
I think this is working as per the code. The credentials are not retained by default when we export/import the flows into Node Red. We need to specify them manually for the first time either in case of fresh flow / for the first time after importing the flow into node red. No where the credentials getting stored, it has to be specified for the first time.

**Comment by knolleary** [comment]
HI @Lokesh-K-Haralakatta 

the ibmiot nodes use a very old mechanism for maintaining their credentials - where they manually make http requests to get/set them. This was how we did it in the very early days of node-red, but we soon added a more formal structure for nodes to use: http://nodered.org/docs/creating-nodes/credentials

This is the issue that @piotrpad is hitting - because the nodes don't use the proper credential mechanism, it isn't possible to import a completely preconfigured node that includes its credentials. With the proper credential mechanism, that is possible to do.

I will open a pull-request with the necessary changes.
