### ISSUE TITLE
JSON payload gives error when is not UTF8

### ISSUE THREAD

**Issue by mirolima** [ibm-watson-iot/iot-nodered#32]
When using IBM IoT node, if I send some json/string in a different chartset format, it gives error that the JSON format is unexpected.
To receive that msg in NodeRed, I had to use a MQTT inbound node, convert the payload this way:
`msg.payload = msg.payload.toString("utf8");`

**Comment by carlos-lacerda** [comment]
Your hint saved my day!!!
I faced a similar problem using Java client for MQTT and MQSeries solved with this UTF-8 conversion.
Thank you!

**Comment by slaupster** [comment]
@mirolima was the encoding UTF-16 or UTF-32 ?  If not I don't think its valid JSON:

https://tools.ietf.org/html/rfc7159

"JSON text SHALL be encoded in UTF-8, UTF-16, or UTF-32."

I imagine the same bug might be possible with UTF-16 or UTF-32 encodings though.

**Comment by mirolima** [comment]
@slaupster I think you're right. The JSON string was not a valid one(UTF-8, UTF-16, or UTF-32).

**Comment by amprasanna** [comment]
@mirolima - Can you please confirm if we can close this thread, at this point of time?
