### ISSUE TITLE
can't find node in flows.nodered.org

### ISSUE THREAD

**Issue by andysc** [ibm-watson-iot/iot-nodered#35]
The search keywords in packages.json are not useful for finding the node in http://flows.nodered.org.
It says "node-red", "bluemix", "iotcloud".
It would be far more helpful if it said something like "Watson", "IoT", "Platform", then we'd have a hope of finding it.

**Comment by dceejay** [comment]
Actually this applies across 3/4 of the nodes in this repo... they could all do with some more appropriate / updated key words to aid finding them.
(PS I think they have to be lower case, and it must include node-red or we won't index it at all :-)

**Comment by andysc** [comment]
Thanks Jeff :)
