### ISSUE TITLE
Supporting TLS and SNI for devcie connections

### ISSUE THREAD

**Issue by matsgothe** [ibm-watson-iot/iot-nodered#39]
Watson IoT Platform is adding a Risk and Security Management capability with a Device Connection Policy that may enforce TLS authentication using token and certificates. The implementation depends on SNI extension to TLS. This issue is requesting TLS with SNI extension to be supported by the iot-nodered node. Thanks, /Mats Göthe (mats.gothe@se.ibm.com)

**Comment by amprasanna** [comment]
This feature is supported starting [node-red-contrib-ibm-watson-iot 0.2.8](https://www.npmjs.com/package/node-red-contrib-ibm-watson-iot)
