### ISSUE TITLE
Use a variable to set identifiers instead of constants

### ISSUE THREAD

**Issue by chlau** [ibm-watson-iot/iot-nodered#40]
I would like to use a variable instead of constants for the list of identifiers to send the push notification. It is not clear how to accomplish this. 

It is also not clear if I set msg.mode in a function node that is input to the pushNotification node that it is actually being honored. Is there a way I can verify if it is working properly?

**Comment by mathieuedet** [comment]
I've exactly the same problem...

**Comment by jeffdare** [comment]
Hi @chlau & @mathieuedet 
Currently you cannot send it as a variable from the flow. But let me raise a PL and add this enhancement.

**Comment by jeffdare** [comment]
This is fixed and now you can send the identifiers as variables from the flow. Please ensure you use the latest version on this node.
