### ISSUE TITLE
iot app node does not get mqtt_host from VCAP_SERVICES

### ISSUE THREAD

**Issue by slaupster** [ibm-watson-iot/iot-nodered#41]
as a result it incorrectly assumes the messaging domain is messaging.internetofthings.ibmcloud.com.  This is not true in dedicated/local and China Bluemix.

All nodes should check the service mqtt_host (for mqtt) and http_host (for rest) when configured with a service, and also allow the specification of these hosts when not configured with a service.

**Comment by amitmangalvedkar** [comment]
Closing this issue after discussion with Paul as the code fix has gone in the previous builds.
